//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace OtoGaleri.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Araclar
    {
        public int Id { get; set; }
        public string A_Marka { get; set; }
        public string A_Plaka { get; set; }
        public Nullable<int> M_Id { get; set; }
    }
}
