//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace OtoGaleri.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class OtoGaleriEntities : DbContext
    {
        public OtoGaleriEntities()
            : base("name=OtoGaleriEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public DbSet<Adminler> Adminlers { get; set; }
        public DbSet<Araclar> Araclars { get; set; }
        public DbSet<Kullanicilar> Kullanicilars { get; set; }
        public DbSet<Musteriler> Musterilers { get; set; }
        public DbSet<Subeler> Subelers { get; set; }
    }
}
